CREATE TABLE IF NOT EXISTS bookmark_labels (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE bookmarks ADD COLUMN label_id INTEGER REFERENCES bookmark_labels(id) ON DELETE SET NULL;
